# Generated by Django 3.2.16 on 2023-01-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230111_0519'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['field_1', 'field_2'], name='services_su_field_1_1ec1d4_idx'),
        ),
    ]
